name: Bootstrap Dev branch (0.0.0-dev)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Base ref (branch/tag) to create new release branch from (e.g., druid-26.0.0)'
        required: true
      product-version:
        description: 'Which version of the product is this branch about? (e.g., 26.0.0)'
        required: true
      sdp-version:
        description: 'Which SDP version is this for (e.g., 25.3)'
        required: true

permissions:
  contents: write

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Create new branch
        run: |
          NEW_BRANCH="stackable/development/${{ github.event.inputs.sdp-version }}/${{ github.event.inputs.product-version }}"
          git checkout -b "$NEW_BRANCH"
          git push origin "$NEW_BRANCH"
